### ISSUE TITLE
QA - Report

### ISSUE THREAD

**Issue by ChialiT** [VoiceDeck/app#45]
March 6th QA,

- [improvement] Category should be able to be disabled by click again. typical UX expectation when a btn (toggle alike), it should be able to toggle it off, in this case, we should allow user to click again and disable.
<img width="364" alt="image" src="https://github.com/VoiceDeck/app/assets/16527634/93ac2708-23c9-4980-b5fb-02acd2c178e9">

- [improvement] might need to an indicator when a filter is applied. now after user set up some filter, it doesn't look like there is anything selected when the modal is closed.
<img width="1346" alt="image" src="https://github.com/VoiceDeck/app/assets/16527634/4acd721f-bfcb-499b-929b-842b30bb192c">

- [bug] reset btn doesn't reset the "active" state on the categories tag, although the URL is resetted
<img width="1377" alt="image" src="https://github.com/VoiceDeck/app/assets/16527634/a8adc954-affd-4802-a121-6c2dfb80e84c">

- [bug] the price slider is not as responsive as expected. try to drag but its stuck on certain range. 
<img width="511" alt="image" src="https://github.com/VoiceDeck/app/assets/16527634/60b35c07-d15f-4757-98a2-0ec293d58244">

- [Improvement] "apply" btn can be bigger
<img width="822" alt="image" src="https://github.com/VoiceDeck/app/assets/16527634/4105e8b6-d539-4253-a8f3-9ebcaac14e93">

- [improvement] when input field is focus, and user finish enter the value, the page will stay as zoomed
<img width="813" alt="image" src="https://github.com/VoiceDeck/app/assets/16527634/42fa1980-6581-41d9-9ecb-67d8c3878394">

**Comment by CJ-Rose** [comment]
https://github.com/VoiceDeck/app/assets/79813968/21199d84-92ff-4668-aeee-144517574fbb

updated: category selections can be toggled on and off, reset button now reflects when tag is not active.

**Comment by CJ-Rose** [comment]
<img width="326" alt="Screenshot 2024-03-07 at 4 17 49 PM" src="https://github.com/VoiceDeck/app/assets/79813968/5831fe2e-201f-4aa8-a415-75efb8f88214">
<img width="326" alt="Screenshot 2024-03-07 at 4 18 03 PM" src="https://github.com/VoiceDeck/app/assets/79813968/9df720ea-e380-496f-b054-bae920289b8d">

updated: filter trigger shows icon when none applied, number of filters shown in blue circle when some. Resets to icon when Reset button clicked.

**Comment by CJ-Rose** [comment]
<img width="489" alt="Screenshot 2024-03-07 at 4 23 19 PM" src="https://github.com/VoiceDeck/app/assets/79813968/aa37c8f1-d87c-4b67-b8a1-ff670f8ed6be">

updated: the silder can now select amounts with a minimum range of $50. This is a slight improvement from before and hopefully seems less arbitrary, but it is not possible to make the range any smaller bc it has to accommodate amounts from $0-$1000 - which looks like this:
<img width="489" alt="Screenshot 2024-03-07 at 4 33 42 PM" src="https://github.com/VoiceDeck/app/assets/79813968/d1e69c76-8310-42eb-b477-f6eddec2abc9">

<img width="489" alt="Screenshot 2024-03-07 at 4 34 06 PM" src="https://github.com/VoiceDeck/app/assets/79813968/4bb43422-c668-4363-b3e5-e474ad1d3728">

**Comment by CJ-Rose** [comment]
updated: larger "apply" buttons
<img width="407" alt="Screenshot 2024-03-07 at 4 36 52 PM" src
="https://github.com/VoiceDeck/app/assets/79813968/073b9a9e-9e4f-4ea4-ad2d-9f07a4a01a0a">

<img width="506" alt="Screenshot 2024-03-07 at 4 38 47 PM" src="https://github.com/VoiceDeck/app/assets/79813968/e3cc21f7-7cc5-475d-9e2d-9e3aa14f1355">

**Comment by CJ-Rose** [comment]
updated: no screen zoom triggered when user taps into search bar on mobile.
the fix was to increase the text size, which i don't love that it's now bigger than tin he other elements in the reports header but i think this is the best way to go. Other possible fixes potentially mess with accessibility.

**Comment by CJ-Rose** [comment]
@ChialiT  complete on this round, maybe open a new issue with additional testing feedback?

**Comment by CJ-Rose** [comment]
closed by #41
